package com.projectspace.foodpackproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.xml.bind.annotation.XmlRootElement
public class CentersAndDrivers implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("centers")
	private java.util.List<java.lang.String> centers;
	@org.kie.api.definition.type.Label("drivers")
	private java.util.List<java.lang.String> drivers;

	public CentersAndDrivers() {
	}

	public java.util.List<java.lang.String> getCenters() {
		return this.centers;
	}

	public void setCenters(java.util.List<java.lang.String> centers) {
		this.centers = centers;
	}

	public java.util.List<java.lang.String> getDrivers() {
		return this.drivers;
	}

	public void setDrivers(java.util.List<java.lang.String> drivers) {
		this.drivers = drivers;
	}

	public CentersAndDrivers(java.util.List<java.lang.String> centers,
			java.util.List<java.lang.String> drivers) {
		this.centers = centers;
		this.drivers = drivers;
	}

}