package com.projectspace.foodpackproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.xml.bind.annotation.XmlRootElement
public class CheckDeliveryCarsResponse implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String status;

	public CheckDeliveryCarsResponse() {
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public CheckDeliveryCarsResponse(java.lang.String status) {
		this.status = status;
	}

}