package com.projectspace.foodpackproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.xml.bind.annotation.XmlRootElement
public class ChefResponse implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String chefResponse;

	public ChefResponse() {
	}

	public java.lang.String getChefResponse() {
		return this.chefResponse;
	}

	public void setChefResponse(java.lang.String chefResponse) {
		this.chefResponse = chefResponse;
	}

	public ChefResponse(java.lang.String chefResponse) {
		this.chefResponse = chefResponse;
	}

}