package com.projectspace.foodpackproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.xml.bind.annotation.XmlRootElement
public class Ingredient implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;
	private java.util.Date date_of_creation;
	@org.kie.api.definition.type.Description("Number of days before the ingredient ceases to be fresh.")
	private java.lang.Integer freshness_limit;

	public Ingredient() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.util.Date getDate_of_creation() {
		return this.date_of_creation;
	}

	public void setDate_of_creation(java.util.Date date_of_creation) {
		this.date_of_creation = date_of_creation;
	}

	public java.lang.Integer getFreshness_limit() {
		return this.freshness_limit;
	}

	public void setFreshness_limit(java.lang.Integer freshness_limit) {
		this.freshness_limit = freshness_limit;
	}

	public Ingredient(java.lang.String name, java.util.Date date_of_creation,
			java.lang.Integer freshness_limit) {
		this.name = name;
		this.date_of_creation = date_of_creation;
		this.freshness_limit = freshness_limit;
	}

}