package com.projectspace.foodpackproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class IngredientValidationError implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean valid;

	public IngredientValidationError() {
	}

	public java.lang.Boolean getValid() {
		return this.valid;
	}

	public void setValid(java.lang.Boolean valid) {
		this.valid = valid;
	}

	public IngredientValidationError(java.lang.Boolean valid) {
		this.valid = valid;
	}

}