package com.projectspace.foodpackproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Recipe implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Recipe Name")
	private java.lang.String name;
	@org.kie.api.definition.type.Description("Full name of the author")
	@org.kie.api.definition.type.Label("Author Name")
	private java.lang.String author;
	@org.kie.api.definition.type.Description("Ingredients that are needed to prepeare meal by the recipe.")
	@org.kie.api.definition.type.Label("List of ingredients")
	private String ingredients;
	@org.kie.api.definition.type.Description("Guide how to prepeare meal by the recipe.")
	@org.kie.api.definition.type.Label("Guide")
	private java.lang.String guide;

	@org.kie.api.definition.type.Description("Author of the recipe will be notified by email that his recipe was approved and requested to prepeare a meal by the recipe for futher development.")
	@org.kie.api.definition.type.Label("Email of Author")
	private java.lang.String authoremail;

	public Recipe() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getAuthor() {
		return this.author;
	}

	public void setAuthor(java.lang.String author) {
		this.author = author;
	}

	public java.lang.String getGuide() {
		return this.guide;
	}

	public void setGuide(java.lang.String guide) {
		this.guide = guide;
	}

	public java.lang.String getAuthoremail() {
		return this.authoremail;
	}

	public void setAuthoremail(java.lang.String authoremail) {
		this.authoremail = authoremail;
	}

	public java.lang.String getIngredients() {
		return this.ingredients;
	}

	public void setIngredients(java.lang.String ingredients) {
		this.ingredients = ingredients;
	}

	public Recipe(java.lang.String name, java.lang.String author,
			java.lang.String ingredients, java.lang.String guide,
			java.lang.String authoremail) {
		this.name = name;
		this.author = author;
		this.ingredients = ingredients;
		this.guide = guide;
		this.authoremail = authoremail;
	}

}