package com.projectspace.foodpackproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.xml.bind.annotation.XmlRootElement
public class UserFeedback implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String feedback;

	public UserFeedback() {
	}

	public java.lang.String getFeedback() {
		return this.feedback;
	}

	public void setFeedback(java.lang.String feedback) {
		this.feedback = feedback;
	}

	public UserFeedback(java.lang.String feedback) {
		this.feedback = feedback;
	}

}